version: '3.3'
services:
  sma-backend:
    image: sma-backend:test
    build: .
    ports:
      - "5000:5000"
    stdin_open: true
    # volumes:
    #   - .:/smart-contract-analyzer-backend
    tty: true
    env_file:
      - .env.development
    depends_on:
      - db
  db:
    image: mongo:7.0.3
    hostname: hduoc2003
    ports:
      - "27017:27017"
    env_file:
      - .env.mongodb
