version: "3.7"

services:
  flask:
    build: ./app
    container_name: app
    restart: always
    environment:
      - ENVIRONMENT=production
      - DATABASE_NAME=TOOL-TEST
      - MONGO_CONNECTION_STRING=mongodb+srv://shodydosh:dT8NJQfeB25rAtj@cluster0.l96vywb.mongodb.net/
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"