version: '3.4'
services:
  sma-backend:
    image: sma-backend:gunicorn
    build: .
    ports:
      - "5000:5000"
    stdin_open: true
    # volumes:
    #   - .:/smart-contract-analyzer-backend
    tty: true
    env_file:
      - .env.development
