version: '2'
services:
  app:
    build: .
    ports:
      - "88:80"
    restart: always #if make changes in this file
    volumes:
      - /var/www/apache-flask:/var/www/apache-flask
      - /var/run/docker.sock:/var/run/docker.sock 
      # use the host's kelnel (use host's Docker socket), to get the Docker not in Docker 
      #https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/
      - "./.htaccess:/var/www/html/.htaccess"
