version: '1'
services:
  app:
    build: .
    ports:
      - "88:80"
    restart: always
    volumes:
      - /var/www/apache-flask:/var/www/apache-flask
      - /var/run/docker.sock:/var/run/docker.sock
